upper = {
    'A': '𝔸',  # U1D538    MATHEMATICAL DOUBLE-STRUCK CAPITAL A
    'B': '𝔹',  # U1D539    MATHEMATICAL DOUBLE-STRUCK CAPITAL B
    'C': 'ℂ',  # U2102    DOUBLE-STRUCK CAPITAL C
    'D': '𝔻',  # U1D53B    MATHEMATICAL DOUBLE-STRUCK CAPITAL D
    'E': '𝔼',  # U1D53C    MATHEMATICAL DOUBLE-STRUCK CAPITAL E
    'F': '𝔽',  # U1D53D    MATHEMATICAL DOUBLE-STRUCK CAPITAL F
    'G': '𝔾',  # U1D53E    MATHEMATICAL DOUBLE-STRUCK CAPITAL G
    'H': 'ℍ',  # U210D    DOUBLE-STRUCK CAPITAL H
    'I': '𝕀',  # U1D540    MATHEMATICAL DOUBLE-STRUCK CAPITAL I
    'J': '𝕁',  # U1D541    MATHEMATICAL DOUBLE-STRUCK CAPITAL J
    'K': '𝕂',  # U1D542    MATHEMATICAL DOUBLE-STRUCK CAPITAL K
    'L': '𝕃',  # U1D543    MATHEMATICAL DOUBLE-STRUCK CAPITAL L
    'M': '𝕄',  # U1D544    MATHEMATICAL DOUBLE-STRUCK CAPITAL M
    'N': 'ℕ',  # U2115    DOUBLE-STRUCK CAPITAL N
    'O': '𝕆',  # U1D546    MATHEMATICAL DOUBLE-STRUCK CAPITAL O
    'P': 'ℙ',  # U2119    DOUBLE-STRUCK CAPITAL P
    'Q': 'ℚ',  # U211A    DOUBLE-STRUCK CAPITAL Q
    'R': 'ℝ',  # U211D    DOUBLE-STRUCK CAPITAL R
    'S': '𝕊',  # U1D54A    MATHEMATICAL DOUBLE-STRUCK CAPITAL S
    'T': '𝕋',  # U1D54B    MATHEMATICAL DOUBLE-STRUCK CAPITAL T
    'U': '𝕌',  # U1D54C    MATHEMATICAL DOUBLE-STRUCK CAPITAL U
    'V': '𝕍',  # U1D54D    MATHEMATICAL DOUBLE-STRUCK CAPITAL V
    'W': '𝕎',  # U1D54E    MATHEMATICAL DOUBLE-STRUCK CAPITAL W
    'X': '𝕏',  # U1D54F    MATHEMATICAL DOUBLE-STRUCK CAPITAL X
    'Y': '𝕐',  # U1D550    MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
    'Z': 'ℤ',  # U2124    DOUBLE-STRUCK CAPITAL Z
}

lower = {
    'a': '𝕒',  # U1D552    MATHEMATICAL DOUBLE-STRUCK SMALL A
    'b': '𝕓',  # U1D553    MATHEMATICAL DOUBLE-STRUCK SMALL B
    'c': '𝕔',  # U1D554    MATHEMATICAL DOUBLE-STRUCK SMALL C
    'd': '𝕕',  # U1D555    MATHEMATICAL DOUBLE-STRUCK SMALL D
    'e': '𝕖',  # U1D556    MATHEMATICAL DOUBLE-STRUCK SMALL E
    'f': '𝕗',  # U1D557    MATHEMATICAL DOUBLE-STRUCK SMALL F
    'g': '𝕘',  # U1D558    MATHEMATICAL DOUBLE-STRUCK SMALL G
    'h': '𝕙',  # U1D559    MATHEMATICAL DOUBLE-STRUCK SMALL H
    'i': '𝕚',  # U1D55A    MATHEMATICAL DOUBLE-STRUCK SMALL I
    'j': '𝕛',  # U1D55B    MATHEMATICAL DOUBLE-STRUCK SMALL J
    'k': '𝕜',  # U1D55C    MATHEMATICAL DOUBLE-STRUCK SMALL K
    'l': '𝕝',  # U1D55D    MATHEMATICAL DOUBLE-STRUCK SMALL L
    'm': '𝕞',  # U1D55E    MATHEMATICAL DOUBLE-STRUCK SMALL M
    'n': '𝕟',  # U1D55F    MATHEMATICAL DOUBLE-STRUCK SMALL N
    'o': '𝕠',  # U1D560    MATHEMATICAL DOUBLE-STRUCK SMALL O
    'p': '𝕡',  # U1D561    MATHEMATICAL DOUBLE-STRUCK SMALL P
    'q': '𝕢',  # U1D562    MATHEMATICAL DOUBLE-STRUCK SMALL Q
    'r': '𝕣',  # U1D563    MATHEMATICAL DOUBLE-STRUCK SMALL R
    's': '𝕤',  # U1D564    MATHEMATICAL DOUBLE-STRUCK SMALL S
    't': '𝕥',  # U1D565    MATHEMATICAL DOUBLE-STRUCK SMALL T
    'u': '𝕦',  # U1D566    MATHEMATICAL DOUBLE-STRUCK SMALL U
    'v': '𝕧',  # U1D567    MATHEMATICAL DOUBLE-STRUCK SMALL V
    'w': '𝕨',  # U1D568    MATHEMATICAL DOUBLE-STRUCK SMALL W
    'x': '𝕩',  # U1D569    MATHEMATICAL DOUBLE-STRUCK SMALL X
    'y': '𝕪',  # U1D56A    MATHEMATICAL DOUBLE-STRUCK SMALL Y
    'z': '𝕫',  # U1D56B    MATHEMATICAL DOUBLE-STRUCK SMALL Z
}
