upper = {
    'A': '𝑨',  # U1D468    MATHEMATICAL BOLD ITALIC CAPITAL A
    'B': '𝑩',  # U1D469    MATHEMATICAL BOLD ITALIC CAPITAL B
    'C': '𝑪',  # U1D46A    MATHEMATICAL BOLD ITALIC CAPITAL C
    'D': '𝑫',  # U1D46B    MATHEMATICAL BOLD ITALIC CAPITAL D
    'E': '𝑬',  # U1D46C    MATHEMATICAL BOLD ITALIC CAPITAL E
    'F': '𝑭',  # U1D46D    MATHEMATICAL BOLD ITALIC CAPITAL F
    'G': '𝑮',  # U1D46E    MATHEMATICAL BOLD ITALIC CAPITAL G
    'H': '𝑯',  # U1D46F    MATHEMATICAL BOLD ITALIC CAPITAL H
    'I': '𝑰',  # U1D470    MATHEMATICAL BOLD ITALIC CAPITAL I
    'J': '𝑱',  # U1D471    MATHEMATICAL BOLD ITALIC CAPITAL J
    'K': '𝑲',  # U1D472    MATHEMATICAL BOLD ITALIC CAPITAL K
    'L': '𝑳',  # U1D473    MATHEMATICAL BOLD ITALIC CAPITAL L
    'M': '𝑴',  # U1D474    MATHEMATICAL BOLD ITALIC CAPITAL M
    'N': '𝑵',  # U1D475    MATHEMATICAL BOLD ITALIC CAPITAL N
    'O': '𝑶',  # U1D476    MATHEMATICAL BOLD ITALIC CAPITAL O
    'P': '𝑷',  # U1D477    MATHEMATICAL BOLD ITALIC CAPITAL P
    'Q': '𝑸',  # U1D478    MATHEMATICAL BOLD ITALIC CAPITAL Q
    'R': '𝑹',  # U1D479    MATHEMATICAL BOLD ITALIC CAPITAL R
    'S': '𝑺',  # U1D47A    MATHEMATICAL BOLD ITALIC CAPITAL S
    'T': '𝑻',  # U1D47B    MATHEMATICAL BOLD ITALIC CAPITAL T
    'U': '𝑼',  # U1D47C    MATHEMATICAL BOLD ITALIC CAPITAL U
    'V': '𝑽',  # U1D47D    MATHEMATICAL BOLD ITALIC CAPITAL V
    'W': '𝑾',  # U1D47E    MATHEMATICAL BOLD ITALIC CAPITAL W
    'X': '𝑿',  # U1D47F    MATHEMATICAL BOLD ITALIC CAPITAL X
    'Y': '𝒀',  # U1D480    MATHEMATICAL BOLD ITALIC CAPITAL Y
    'Z': '𝒁',  # U1D481    MATHEMATICAL BOLD ITALIC CAPITAL Z
}

lower = {
    'a': '𝒂',  # U1D482    MATHEMATICAL BOLD ITALIC SMALL A
    'b': '𝒃',  # U1D483    MATHEMATICAL BOLD ITALIC SMALL B
    'c': '𝒄',  # U1D484    MATHEMATICAL BOLD ITALIC SMALL C
    'd': '𝒅',  # U1D485    MATHEMATICAL BOLD ITALIC SMALL D
    'e': '𝒆',  # U1D486    MATHEMATICAL BOLD ITALIC SMALL E
    'f': '𝒇',  # U1D487    MATHEMATICAL BOLD ITALIC SMALL F
    'g': '𝒈',  # U1D488    MATHEMATICAL BOLD ITALIC SMALL G
    'h': '𝒉',  # U1D489    MATHEMATICAL BOLD ITALIC SMALL H
    'i': '𝒊',  # U1D48A    MATHEMATICAL BOLD ITALIC SMALL I
    'j': '𝒋',  # U1D48B    MATHEMATICAL BOLD ITALIC SMALL J
    'k': '𝒌',  # U1D48C    MATHEMATICAL BOLD ITALIC SMALL K
    'l': '𝒍',  # U1D48D    MATHEMATICAL BOLD ITALIC SMALL L
    'm': '𝒎',  # U1D48E    MATHEMATICAL BOLD ITALIC SMALL M
    'n': '𝒏',  # U1D48F    MATHEMATICAL BOLD ITALIC SMALL N
    'o': '𝒐',  # U1D490    MATHEMATICAL BOLD ITALIC SMALL O
    'p': '𝒑',  # U1D491    MATHEMATICAL BOLD ITALIC SMALL P
    'q': '𝒒',  # U1D492    MATHEMATICAL BOLD ITALIC SMALL Q
    'r': '𝒓',  # U1D493    MATHEMATICAL BOLD ITALIC SMALL R
    's': '𝒔',  # U1D494    MATHEMATICAL BOLD ITALIC SMALL S
    't': '𝒕',  # U1D495    MATHEMATICAL BOLD ITALIC SMALL T
    'u': '𝒖',  # U1D496    MATHEMATICAL BOLD ITALIC SMALL U
    'v': '𝒗',  # U1D497    MATHEMATICAL BOLD ITALIC SMALL V
    'w': '𝒘',  # U1D498    MATHEMATICAL BOLD ITALIC SMALL W
    'x': '𝒙',  # U1D499    MATHEMATICAL BOLD ITALIC SMALL X
    'y': '𝒚',  # U1D49A    MATHEMATICAL BOLD ITALIC SMALL Y
    'z': '𝒛',  # U1D49B    MATHEMATICAL BOLD ITALIC SMALL Z
}
