lower = {
    'a': '𝐚',  # U1D41A    MATHEMATICAL BOLD SMALL A
    'b': '𝐛',  # U1D41B    MATHEMATICAL BOLD SMALL B
    'c': '𝐜',  # U1D41C    MATHEMATICAL BOLD SMALL C
    'd': '𝐝',  # U1D41D    MATHEMATICAL BOLD SMALL D
    'e': '𝐞',  # U1D41E    MATHEMATICAL BOLD SMALL E
    'f': '𝐟',  # U1D41F    MATHEMATICAL BOLD SMALL F
    'g': '𝐠',  # U1D420    MATHEMATICAL BOLD SMALL G
    'h': '𝐡',  # U1D421    MATHEMATICAL BOLD SMALL H
    'i': '𝐢',  # U1D422    MATHEMATICAL BOLD SMALL I
    'j': '𝐣',  # U1D423    MATHEMATICAL BOLD SMALL J
    'k': '𝐤',  # U1D424    MATHEMATICAL BOLD SMALL K
    'l': '𝐥',  # U1D425    MATHEMATICAL BOLD SMALL L
    'm': '𝐦',  # U1D426    MATHEMATICAL BOLD SMALL M
    'n': '𝐧',  # U1D427    MATHEMATICAL BOLD SMALL N
    'o': '𝐨',  # U1D428    MATHEMATICAL BOLD SMALL O
    'p': '𝐩',  # U1D429    MATHEMATICAL BOLD SMALL P
    'q': '𝐪',  # U1D42A    MATHEMATICAL BOLD SMALL Q
    'r': '𝐫',  # U1D42B    MATHEMATICAL BOLD SMALL R
    's': '𝐬',  # U1D42C    MATHEMATICAL BOLD SMALL S
    't': '𝐭',  # U1D42D    MATHEMATICAL BOLD SMALL T
    'u': '𝐮',  # U1D42E    MATHEMATICAL BOLD SMALL U
    'v': '𝐯',  # U1D42F    MATHEMATICAL BOLD SMALL V
    'w': '𝐰',  # U1D430    MATHEMATICAL BOLD SMALL W
    'x': '𝐱',  # U1D431    MATHEMATICAL BOLD SMALL X
    'y': '𝐲',  # U1D432    MATHEMATICAL BOLD SMALL Y
    'z': '𝐳',  # U1D433    MATHEMATICAL BOLD SMALL Z
}

upper = {
    'A': '𝐀',  # U1D400    MATHEMATICAL BOLD CAPITAL A
    'B': '𝐁',  # U1D401    MATHEMATICAL BOLD CAPITAL B
    'C': '𝐂',  # U1D402    MATHEMATICAL BOLD CAPITAL C
    'D': '𝐃',  # U1D403    MATHEMATICAL BOLD CAPITAL D
    'E': '𝐄',  # U1D404    MATHEMATICAL BOLD CAPITAL E
    'F': '𝐅',  # U1D405    MATHEMATICAL BOLD CAPITAL F
    'G': '𝐆',  # U1D406    MATHEMATICAL BOLD CAPITAL G
    'H': '𝐇',  # U1D407    MATHEMATICAL BOLD CAPITAL H
    'I': '𝐈',  # U1D408    MATHEMATICAL BOLD CAPITAL I
    'J': '𝐉',  # U1D409    MATHEMATICAL BOLD CAPITAL J
    'K': '𝐊',  # U1D40A    MATHEMATICAL BOLD CAPITAL K
    'L': '𝐋',  # U1D40B    MATHEMATICAL BOLD CAPITAL L
    'M': '𝐌',  # U1D40C    MATHEMATICAL BOLD CAPITAL M
    'N': '𝐍',  # U1D40D    MATHEMATICAL BOLD CAPITAL N
    'O': '𝐎',  # U1D40E    MATHEMATICAL BOLD CAPITAL O
    'P': '𝐏',  # U1D40F    MATHEMATICAL BOLD CAPITAL P
    'Q': '𝐐',  # U1D410    MATHEMATICAL BOLD CAPITAL Q
    'R': '𝐑',  # U1D411    MATHEMATICAL BOLD CAPITAL R
    'S': '𝐒',  # U1D412    MATHEMATICAL BOLD CAPITAL S
    'T': '𝐓',  # U1D413    MATHEMATICAL BOLD CAPITAL T
    'U': '𝐔',  # U1D414    MATHEMATICAL BOLD CAPITAL U
    'V': '𝐕',  # U1D415    MATHEMATICAL BOLD CAPITAL V
    'W': '𝐖',  # U1D416    MATHEMATICAL BOLD CAPITAL W
    'X': '𝐗',  # U1D417    MATHEMATICAL BOLD CAPITAL X
    'Y': '𝐘',  # U1D418    MATHEMATICAL BOLD CAPITAL Y
    'Z': '𝐙'  # U1D419    MATHEMATICAL BOLD CAPITAL Z
}
