lower = {
    'a': '𝒶',  # U1D4B6    MATHEMATICAL SCRIPT SMALL A
    'b': '𝒷',  # U1D4B7    MATHEMATICAL SCRIPT SMALL B
    'c': '𝒸',  # U1D4B8    MATHEMATICAL SCRIPT SMALL C
    'd': '𝒹',  # U1D4B9    MATHEMATICAL SCRIPT SMALL D
    'e': 'ℯ',  # U212F    SCRIPT SMALL E
    'f': '𝒻',  # U1D4BB    MATHEMATICAL SCRIPT SMALL F
    'g': 'ℊ',  # U210A    SCRIPT SMALL G
    'h': '𝒽',  # U1D4BD    MATHEMATICAL SCRIPT SMALL H
    'i': '𝒾',  # U1D4BE    MATHEMATICAL SCRIPT SMALL I
    'j': '𝒿',  # U1D4BF    MATHEMATICAL SCRIPT SMALL J
    'k': '𝓀',  # U1D4C0    MATHEMATICAL SCRIPT SMALL K
    'l': '𝓁',  # U1D4C1    MATHEMATICAL SCRIPT SMALL L
    'm': '𝓂',  # U1D4C2    MATHEMATICAL SCRIPT SMALL M
    'n': '𝓃',  # U1D4C3    MATHEMATICAL SCRIPT SMALL N
    'o': 'ℴ',  # U2134    SCRIPT SMALL O
    'p': '𝓅',  # U1D4C5    MATHEMATICAL SCRIPT SMALL P
    'q': '𝓆',  # U1D4C6    MATHEMATICAL SCRIPT SMALL Q
    'r': '𝓇',  # U1D4C7    MATHEMATICAL SCRIPT SMALL R
    's': '𝓈',  # U1D4C8    MATHEMATICAL SCRIPT SMALL S
    't': '𝓉',  # U1D4C9    MATHEMATICAL SCRIPT SMALL T
    'u': '𝓊',  # U1D4CA    MATHEMATICAL SCRIPT SMALL U
    'v': '𝓋',  # U1D4CB    MATHEMATICAL SCRIPT SMALL V
    'w': '𝓌',  # U1D4CC    MATHEMATICAL SCRIPT SMALL W
    'x': '𝓍',  # U1D4CD    MATHEMATICAL SCRIPT SMALL X
    'y': '𝓎',  # U1D4CE    MATHEMATICAL SCRIPT SMALL Y
    'z': '𝓏',  # U1D4CF    MATHEMATICAL SCRIPT SMALL Z
}

upper = {
    'A': '𝒜',  # U1D49C    MATHEMATICAL SCRIPT CAPITAL A
    'B': 'ℬ',  # U212C    SCRIPT CAPITAL B
    'C': '𝒞',  # U1D49E    MATHEMATICAL SCRIPT CAPITAL C
    'D': '𝒟',  # U1D49F    MATHEMATICAL SCRIPT CAPITAL D
    'E': 'ℰ',  # U2130    SCRIPT CAPITAL E
    'F': 'ℱ',  # U2131    SCRIPT CAPITAL F
    'G': '𝒢',  # U1D4A2    MATHEMATICAL SCRIPT CAPITAL G
    'H': 'ℋ',  # U210B    SCRIPT CAPITAL H
    'I': 'ℐ',  # U2110    SCRIPT CAPITAL I
    'J': '𝒥',  # U1D4A5    MATHEMATICAL SCRIPT CAPITAL J
    'K': '𝒦',  # U1D4A6    MATHEMATICAL SCRIPT CAPITAL K
    'L': 'ℒ',  # U2112    SCRIPT CAPITAL L
    'M': 'ℳ',  # U2133    SCRIPT CAPITAL M
    'N': '𝒩',  # U1D4A9    MATHEMATICAL SCRIPT CAPITAL N
    'O': '𝒪',  # U1D4AA    MATHEMATICAL SCRIPT CAPITAL O
    'P': '𝒫',  # U1D4AB    MATHEMATICAL SCRIPT CAPITAL P
    'Q': '𝒬',  # U1D4AC    MATHEMATICAL SCRIPT CAPITAL Q
    'R': 'ℛ',  # U211B    SCRIPT CAPITAL R
    'S': '𝒮',  # U1D4AE    MATHEMATICAL SCRIPT CAPITAL S
    'T': '𝒯',  # U1D4AF    MATHEMATICAL SCRIPT CAPITAL T
    'U': '𝒰',  # U1D4B0    MATHEMATICAL SCRIPT CAPITAL U
    'V': '𝒱',  # U1D4B1    MATHEMATICAL SCRIPT CAPITAL V
    'W': '𝒲',  # U1D4B2    MATHEMATICAL SCRIPT CAPITAL W
    'X': '𝒳',  # U1D4B3    MATHEMATICAL SCRIPT CAPITAL X
    'Y': '𝒴',  # U1D4B4    MATHEMATICAL SCRIPT CAPITAL Y
    'Z': '𝒵',  # U1D4B5    MATHEMATICAL SCRIPT CAPITAL Z
}
