upper = {
	'A': '𝔄', # U1D504	MATHEMATICAL FRAKTUR CAPITAL A
	'B': '𝔅', # U1D505	MATHEMATICAL FRAKTUR CAPITAL B
	'D': '𝔇', # U1D507	MATHEMATICAL FRAKTUR CAPITAL D
	'E': '𝔈', # U1D508	MATHEMATICAL FRAKTUR CAPITAL E
	'F': '𝔉', # U1D509	MATHEMATICAL FRAKTUR CAPITAL F
	'G': '𝔊', # U1D50A	MATHEMATICAL FRAKTUR CAPITAL G
	'J': '𝔍', # U1D50D	MATHEMATICAL FRAKTUR CAPITAL J
	'K': '𝔎', # U1D50E	MATHEMATICAL FRAKTUR CAPITAL K
	'L': '𝔏', # U1D50F	MATHEMATICAL FRAKTUR CAPITAL L
	'M': '𝔐', # U1D510	MATHEMATICAL FRAKTUR CAPITAL M
	'N': '𝔑', # U1D511	MATHEMATICAL FRAKTUR CAPITAL N
	'O': '𝔒', # U1D512	MATHEMATICAL FRAKTUR CAPITAL O
	'P': '𝔓', # U1D513	MATHEMATICAL FRAKTUR CAPITAL P
	'Q': '𝔔', # U1D514	MATHEMATICAL FRAKTUR CAPITAL Q
	'S': '𝔖', # U1D516	MATHEMATICAL FRAKTUR CAPITAL S
	'T': '𝔗', # U1D517	MATHEMATICAL FRAKTUR CAPITAL T
	'U': '𝔘', # U1D518	MATHEMATICAL FRAKTUR CAPITAL U
	'V': '𝔙', # U1D519	MATHEMATICAL FRAKTUR CAPITAL V
	'W': '𝔚', # U1D51A	MATHEMATICAL FRAKTUR CAPITAL W
	'X': '𝔛', # U1D51B	MATHEMATICAL FRAKTUR CAPITAL X
	'Y': '𝔜', # U1D51C	MATHEMATICAL FRAKTUR CAPITAL Y
}

lower = {
	'a': '𝔞', # U1D51E	MATHEMATICAL FRAKTUR SMALL A
	'b': '𝔟', # U1D51F	MATHEMATICAL FRAKTUR SMALL B
	'c': '𝔠', # U1D520	MATHEMATICAL FRAKTUR SMALL C
	'd': '𝔡', # U1D521	MATHEMATICAL FRAKTUR SMALL D
	'e': '𝔢', # U1D522	MATHEMATICAL FRAKTUR SMALL E
	'f': '𝔣', # U1D523	MATHEMATICAL FRAKTUR SMALL F
	'g': '𝔤', # U1D524	MATHEMATICAL FRAKTUR SMALL G
	'h': '𝔥', # U1D525	MATHEMATICAL FRAKTUR SMALL H
	'i': '𝔦', # U1D526	MATHEMATICAL FRAKTUR SMALL I
	'j': '𝔧', # U1D527	MATHEMATICAL FRAKTUR SMALL J
	'k': '𝔨', # U1D528	MATHEMATICAL FRAKTUR SMALL K
	'l': '𝔩', # U1D529	MATHEMATICAL FRAKTUR SMALL L
	'm': '𝔪', # U1D52A	MATHEMATICAL FRAKTUR SMALL M
	'n': '𝔫', # U1D52B	MATHEMATICAL FRAKTUR SMALL N
	'o': '𝔬', # U1D52C	MATHEMATICAL FRAKTUR SMALL O
	'p': '𝔭', # U1D52D	MATHEMATICAL FRAKTUR SMALL P
	'q': '𝔮', # U1D52E	MATHEMATICAL FRAKTUR SMALL Q
	'r': '𝔯', # U1D52F	MATHEMATICAL FRAKTUR SMALL R
	's': '𝔰', # U1D530	MATHEMATICAL FRAKTUR SMALL S
	't': '𝔱', # U1D531	MATHEMATICAL FRAKTUR SMALL T
	'u': '𝔲', # U1D532	MATHEMATICAL FRAKTUR SMALL U
	'v': '𝔳', # U1D533	MATHEMATICAL FRAKTUR SMALL V
	'w': '𝔴', # U1D534	MATHEMATICAL FRAKTUR SMALL W
	'x': '𝔵', # U1D535	MATHEMATICAL FRAKTUR SMALL X
	'y': '𝔶', # U1D536	MATHEMATICAL FRAKTUR SMALL Y
	'z': '𝔷', # U1D537	MATHEMATICAL FRAKTUR SMALL Z
}
