upper = {
    'A': '𝕬',  # U1D56C    MATHEMATICAL BOLD FRAKTUR CAPITAL A
    'B': '𝕭',  # U1D56D    MATHEMATICAL BOLD FRAKTUR CAPITAL B
    'C': '𝕮',  # U1D56E    MATHEMATICAL BOLD FRAKTUR CAPITAL C
    'D': '𝕯',  # U1D56F    MATHEMATICAL BOLD FRAKTUR CAPITAL D
    'E': '𝕰',  # U1D570    MATHEMATICAL BOLD FRAKTUR CAPITAL E
    'F': '𝕱',  # U1D571    MATHEMATICAL BOLD FRAKTUR CAPITAL F
    'G': '𝕲',  # U1D572    MATHEMATICAL BOLD FRAKTUR CAPITAL G
    'H': '𝕳',  # U1D573    MATHEMATICAL BOLD FRAKTUR CAPITAL H
    'I': '𝕴',  # U1D574    MATHEMATICAL BOLD FRAKTUR CAPITAL I
    'J': '𝕵',  # U1D575    MATHEMATICAL BOLD FRAKTUR CAPITAL J
    'K': '𝕶',  # U1D576    MATHEMATICAL BOLD FRAKTUR CAPITAL K
    'L': '𝕷',  # U1D577    MATHEMATICAL BOLD FRAKTUR CAPITAL L
    'M': '𝕸',  # U1D578    MATHEMATICAL BOLD FRAKTUR CAPITAL M
    'N': '𝕹',  # U1D579    MATHEMATICAL BOLD FRAKTUR CAPITAL N
    'O': '𝕺',  # U1D57A    MATHEMATICAL BOLD FRAKTUR CAPITAL O
    'P': '𝕻',  # U1D57B    MATHEMATICAL BOLD FRAKTUR CAPITAL P
    'Q': '𝕼',  # U1D57C    MATHEMATICAL BOLD FRAKTUR CAPITAL Q
    'R': '𝕽',  # U1D57D    MATHEMATICAL BOLD FRAKTUR CAPITAL R
    'S': '𝕾',  # U1D57E    MATHEMATICAL BOLD FRAKTUR CAPITAL S
    'T': '𝕿',  # U1D57F    MATHEMATICAL BOLD FRAKTUR CAPITAL T
    'U': '𝖀',  # U1D580    MATHEMATICAL BOLD FRAKTUR CAPITAL U
    'V': '𝖁',  # U1D581    MATHEMATICAL BOLD FRAKTUR CAPITAL V
    'W': '𝖂',  # U1D582    MATHEMATICAL BOLD FRAKTUR CAPITAL W
    'X': '𝖃',  # U1D583    MATHEMATICAL BOLD FRAKTUR CAPITAL X
    'Y': '𝖄',  # U1D584    MATHEMATICAL BOLD FRAKTUR CAPITAL Y
    'Z': '𝖅',  # U1D585    MATHEMATICAL BOLD FRAKTUR CAPITAL Z
}

lower = {
    'a': '𝖆',  # U1D586    MATHEMATICAL BOLD FRAKTUR SMALL A
    'b': '𝖇',  # U1D587    MATHEMATICAL BOLD FRAKTUR SMALL B
    'c': '𝖈',  # U1D588    MATHEMATICAL BOLD FRAKTUR SMALL C
    'd': '𝖉',  # U1D589    MATHEMATICAL BOLD FRAKTUR SMALL D
    'e': '𝖊',  # U1D58A    MATHEMATICAL BOLD FRAKTUR SMALL E
    'f': '𝖋',  # U1D58B    MATHEMATICAL BOLD FRAKTUR SMALL F
    'g': '𝖌',  # U1D58C    MATHEMATICAL BOLD FRAKTUR SMALL G
    'h': '𝖍',  # U1D58D    MATHEMATICAL BOLD FRAKTUR SMALL H
    'i': '𝖎',  # U1D58E    MATHEMATICAL BOLD FRAKTUR SMALL I
    'j': '𝖏',  # U1D58F    MATHEMATICAL BOLD FRAKTUR SMALL J
    'k': '𝖐',  # U1D590    MATHEMATICAL BOLD FRAKTUR SMALL K
    'l': '𝖑',  # U1D591    MATHEMATICAL BOLD FRAKTUR SMALL L
    'm': '𝖒',  # U1D592    MATHEMATICAL BOLD FRAKTUR SMALL M
    'n': '𝖓',  # U1D593    MATHEMATICAL BOLD FRAKTUR SMALL N
    'o': '𝖔',  # U1D594    MATHEMATICAL BOLD FRAKTUR SMALL O
    'p': '𝖕',  # U1D595    MATHEMATICAL BOLD FRAKTUR SMALL P
    'q': '𝖖',  # U1D596    MATHEMATICAL BOLD FRAKTUR SMALL Q
    'r': '𝖗',  # U1D597    MATHEMATICAL BOLD FRAKTUR SMALL R
    's': '𝖘',  # U1D598    MATHEMATICAL BOLD FRAKTUR SMALL S
    't': '𝖙',  # U1D599    MATHEMATICAL BOLD FRAKTUR SMALL T
    'u': '𝖚',  # U1D59A    MATHEMATICAL BOLD FRAKTUR SMALL U
    'v': '𝖛',  # U1D59B    MATHEMATICAL BOLD FRAKTUR SMALL V
    'w': '𝖜',  # U1D59C    MATHEMATICAL BOLD FRAKTUR SMALL W
    'x': '𝖝',  # U1D59D    MATHEMATICAL BOLD FRAKTUR SMALL X
    'y': '𝖞',  # U1D59E    MATHEMATICAL BOLD FRAKTUR SMALL Y
    'z': '𝖟',  # U1D59F    MATHEMATICAL BOLD FRAKTUR SMALL Z
}
