upper = {
    'A': '𝐴',  # U1D434    MATHEMATICAL ITALIC CAPITAL A
    'B': '𝐵',  # U1D435    MATHEMATICAL ITALIC CAPITAL B
    'C': '𝐶',  # U1D436    MATHEMATICAL ITALIC CAPITAL C
    'D': '𝐷',  # U1D437    MATHEMATICAL ITALIC CAPITAL D
    'E': '𝐸',  # U1D438    MATHEMATICAL ITALIC CAPITAL E
    'F': '𝐹',  # U1D439    MATHEMATICAL ITALIC CAPITAL F
    'G': '𝐺',  # U1D43A    MATHEMATICAL ITALIC CAPITAL G
    'H': '𝐻',  # U1D43B    MATHEMATICAL ITALIC CAPITAL H
    'I': '𝐼',  # U1D43C    MATHEMATICAL ITALIC CAPITAL I
    'J': '𝐽',  # U1D43D    MATHEMATICAL ITALIC CAPITAL J
    'K': '𝐾',  # U1D43E    MATHEMATICAL ITALIC CAPITAL K
    'L': '𝐿',  # U1D43F    MATHEMATICAL ITALIC CAPITAL L
    'M': '𝑀',  # U1D440    MATHEMATICAL ITALIC CAPITAL M
    'N': '𝑁',  # U1D441    MATHEMATICAL ITALIC CAPITAL N
    'O': '𝑂',  # U1D442    MATHEMATICAL ITALIC CAPITAL O
    'P': '𝑃',  # U1D443    MATHEMATICAL ITALIC CAPITAL P
    'Q': '𝑄',  # U1D444    MATHEMATICAL ITALIC CAPITAL Q
    'R': '𝑅',  # U1D445    MATHEMATICAL ITALIC CAPITAL R
    'S': '𝑆',  # U1D446    MATHEMATICAL ITALIC CAPITAL S
    'T': '𝑇',  # U1D447    MATHEMATICAL ITALIC CAPITAL T
    'U': '𝑈',  # U1D448    MATHEMATICAL ITALIC CAPITAL U
    'V': '𝑉',  # U1D449    MATHEMATICAL ITALIC CAPITAL V
    'W': '𝑊',  # U1D44A    MATHEMATICAL ITALIC CAPITAL W
    'X': '𝑋',  # U1D44B    MATHEMATICAL ITALIC CAPITAL X
    'Y': '𝑌',  # U1D44C    MATHEMATICAL ITALIC CAPITAL Y
    'Z': '𝑍',  # U1D44D    MATHEMATICAL ITALIC CAPITAL Z
}

lower = {
    'a': '𝑎',  # U1D44E    MATHEMATICAL ITALIC SMALL A
    'b': '𝑏',  # U1D44F    MATHEMATICAL ITALIC SMALL B
    'c': '𝑐',  # U1D450    MATHEMATICAL ITALIC SMALL C
    'd': '𝑑',  # U1D451    MATHEMATICAL ITALIC SMALL D
    'e': '𝑒',  # U1D452    MATHEMATICAL ITALIC SMALL E
    'f': '𝑓',  # U1D453    MATHEMATICAL ITALIC SMALL F
    'g': '𝑔',  # U1D454    MATHEMATICAL ITALIC SMALL G

    'i': '𝑖',  # U1D456    MATHEMATICAL ITALIC SMALL I
    'j': '𝑗',  # U1D457    MATHEMATICAL ITALIC SMALL J
    'k': '𝑘',  # U1D458    MATHEMATICAL ITALIC SMALL K
    'l': '𝑙',  # U1D459    MATHEMATICAL ITALIC SMALL L
    'm': '𝑚',  # U1D45A    MATHEMATICAL ITALIC SMALL M
    'n': '𝑛',  # U1D45B    MATHEMATICAL ITALIC SMALL N
    'o': '𝑜',  # U1D45C    MATHEMATICAL ITALIC SMALL O
    'p': '𝑝',  # U1D45D    MATHEMATICAL ITALIC SMALL P
    'q': '𝑞',  # U1D45E    MATHEMATICAL ITALIC SMALL Q
    'r': '𝑟',  # U1D45F    MATHEMATICAL ITALIC SMALL R
    's': '𝑠',  # U1D460    MATHEMATICAL ITALIC SMALL S
    't': '𝑡',  # U1D461    MATHEMATICAL ITALIC SMALL T
    'u': '𝑢',  # U1D462    MATHEMATICAL ITALIC SMALL U
    'v': '𝑣',  # U1D463    MATHEMATICAL ITALIC SMALL V
    'w': '𝑤',  # U1D464    MATHEMATICAL ITALIC SMALL W
    'x': '𝑥',  # U1D465    MATHEMATICAL ITALIC SMALL X
    'y': '𝑦',  # U1D466    MATHEMATICAL ITALIC SMALL Y
    'z': '𝑧',  # U1D467    MATHEMATICAL ITALIC SMALL Z
}
