#! /usr/bin/python3

if __name__ == '__main__':
    # import argparse # TODO
    import sys
    from .imports import tidy

    filename = sys.argv[1]

    print('Tidying import statements in %r' % filename)
    tidy(filename)
    print('Done.')
